services:

    board3.portal.main:
        class: \board3\portal\controller\main
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @path_helper
            - %core.root_path%
            - .%core.php_ext%
